services:
  postgres_db:
    image: postgres:latest
    container_name: product_search_postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    container_name: product_search_redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data: