services:
  product-search:
    image: product-search-service:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: product-search
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}